set(_CATKIN_CURRENT_PACKAGE "gps_navigation")
set(gps_navigation_MAINTAINER "dhrgam79 <dhrgam79@todo.todo>")
set(gps_navigation_DEPRECATED "")
set(gps_navigation_VERSION "0.0.0")
set(gps_navigation_BUILD_DEPENDS "dynamic_reconfigure" "geometry_msgs" "nav_msgs" "roscpp" "sensor_msgs" "std_msgs" "tf" "visualization_msgs")
set(gps_navigation_RUN_DEPENDS "dynamic_reconfigure" "geometry_msgs" "nav_msgs" "roscpp" "sensor_msgs" "std_msgs" "tf" "visualization_msgs")
set(gps_navigation_BUILDTOOL_DEPENDS "catkin")