TrajectoryPlannerROS:
  max_vel_x: 0.15
  min_vel_x: 0.01
  max_rotational_vel: 0.1
  min_in_place_rotational_vel: 0.05

  acc_lim_theta: 0.02
  acc_lim_x: 0.02
  acc_lim_y: 0.02

  holonomic_robot: false

  meter_scoring: false
  pdist_scale: 0.01
  gdist_scale: 0.2
  occdist_scale: 0.03
  heading_scoring_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  simple_attractor: false
  publish_cost_grid_pc: true

  oscillation_reset_dist: 0.25
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1
  
  dwa: true
