TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.01
  max_rotational_vel: 0.2
  min_in_place_rotational_vel: 0.05

  acc_lim_th: 0.1
  acc_lim_x: 0.1
  acc_lim_y: 0.1

  holonomic_robot: false

  