obstacle_range: 4.5
raytrace_range: 2.5
footprint: [[0.6, -0.4], [0.6, 0.4], [-0.6, 0.4], [-0.6, -0.4]]
#robot_radius: 0.33
inflation_radius: 0.2

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
