map_update_interval: 5.0
maxUrange: 9.25
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 8
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 0.0
srr: 0.02
srt: 0.07
str: 0.02
stt: 0.7
linearUpdate: 0.1
angularUpdate: 0.05
temporalUpdate: -1.0
resampleThreshold: 0.5
particles: 50
xmin: -200
ymin: -200
xmax: 200
ymax: 200
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
transform_publish_period: 0.05
occ_thresh: 0.25
maxRange: 10.0

# Misc
inverted_laser: false
throttle_scans: 1
base_frame: base_link
map_frame: map
odom_frame: odom




